mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.kaibo.meteor.dao.pojo
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://118.126.108.24:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Yuxuelian-520
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 5000
      connection-test-query: SELECT 1
  redis:
    host: 118.126.108.24
    port: 6379
    database: 15
    timeout: 5000
    password: Yuxuelian-520
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 1
  security:
    user:
      name: kaibo
      password: kaibo123
  http:
    converters:
      preferred-json-mapper: gson
    encoding:
      charset: utf-8
      force: true
      enabled: true
